name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install aws-cdk-lib # TODO: fix this
        python -m pip install poetry
    - name: Initialize cache
      uses: actions/cache@v2.1.6
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Validate cache
      if: steps.cache.outputs.cache-hit != 'true'
      run: python -m poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
    - name: Configure poetry
      run: |
        poetry debug
        # python -m poetry config virtualenvs.in-project true
        python -m poetry install
    - name: Lint with flake8
      run: |
        flake8 'src' --count --max-line-length=127 --show-source --statistics
    # - name: Test with pytest
    #   run: |
    #     python -m pytest tests/
    #     # pytest --rootdir='$HOME/work/zpipz'
    # - name: Upload code coverage
    #   uses: codecov/codecov-action@v1

